{
    "name": "BenAmor Travel",
    "summary": "BenAmor Travel - gestion complete des dossiers d'agence de voyage",
    "version": "19.0.2.0.0",
    "category": "Services",
    "license": "LGPL-3",
    "author": "BenAmor Travel",
    "depends": [
        "base",
        "mail",
        "contacts",
        "sale_management",
        "purchase",
        "account",
        "analytic",
    ],
    "data": [
        "security/travel_security.xml",
        "security/ir.model.access.csv",
        "data/travel_data.xml",
        "views/travel_referential_views.xml",
        "views/res_partner_views.xml",
        "views/travel_passenger_views.xml",
        "views/travel_service_views.xml",
        "views/travel_file_views.xml",
        "views/travel_dashboard_views.xml",
        "views/travel_analysis_views.xml",
        "views/sale_order_views.xml",
        "views/account_move_views.xml",
        "views/native_actions.xml",
        "views/travel_help_views.xml",
        "views/travel_menus.xml",
        "views/travel_reservation_views.xml",
        "views/product_template_views.xml",
        "report/travel_file_report.xml",
        "report/travel_invoice_report.xml",
    ],
    "application": True,
    "installable": True,
}
